#Name of the magic alter
alterName: "Altare Magico"

#/magic bazar schematic to paste
bazarSchematic: "test"

#Change the text of distance 1 papers to:
personalPaperText: "&5%area% di personale"

wandItem:
  display: "&6Catalizzatore"
  lore:
  - "&8&k111111111111111111111"
  - "&4MAGIA: &5%spell%"
  - "&4Potenza Magica: &5%totalpower%"
  - "&4Livello Minimo: &5%lvl%"
  - "&4Area d'Effetto:"
  - "&5%area% di %distance% Metri"
  - "&4Descrizione:"
  - "&5%description%"

spellItem:
  item: STRUCTURE_VOID
  data: 0
  durability: 0
  name: "&6&lMetamagia"
  lore:
  - '&6&lTipo: &3%type%'
  - '&6&lNome: &3%name%'
  - ' '
  - '&6&lDescrizione: &e%desc%'
  addLore:
  - "&6Price: %price%"

#NPC Name and Skin
npcs:
  paper:
    name: "Paper Bazar"
    skin: "BumbleBeee_"
    addLore:
    - "&6Price: %price%"
  wand:
    name: "Wand Bazar"
    skin: "BumbleBeee_"
    addLore:
    - "&6Price: %price%"
  structure:
    name: "Structure Bazar"
    skin: "BumbleBeee_"
    addLore:
    - "&6Price: %price%"
  altar:
    name: "Alter Bazar"
    skin: "BumbleBeee_"
    addLore:
    - "&6Price: %price%"
  wanditems:
    name: "Wand Item Bazar"
    skin: "BumbleBeee_"
    addLore:
    - "&6Price: %price%"
